// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtvK-1igcyina-QfsT-EB4xP2vJCuncxo',
    appId: '1:767423513180:web:2b33ee43b4e60ea4e61c99',
    messagingSenderId: '767423513180',
    projectId: 'breedward1',
    authDomain: 'breedward1.firebaseapp.com',
    databaseURL: 'https://breedward1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedward1.firebasestorage.app',
    measurementId: 'G-CNM4358NNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuwv3SF-GNUjXMUB010JexwbXz3A_2e7M',
    appId: '1:767423513180:android:f0eaaf407c13f8bde61c99',
    messagingSenderId: '767423513180',
    projectId: 'breedward1',
    databaseURL: 'https://breedward1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedward1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJPA-9wkn5tyNT6lMcoq-DIr-WdNBhS0',
    appId: '1:767423513180:ios:e39bee403f8e9e7de61c99',
    messagingSenderId: '767423513180',
    projectId: 'breedward1',
    databaseURL: 'https://breedward1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedward1.firebasestorage.app',
    iosClientId: '767423513180-pi0es8p0ji701reubuub6t3nns74dfli.apps.googleusercontent.com',
    iosBundleId: 'com.example.breedward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHJPA-9wkn5tyNT6lMcoq-DIr-WdNBhS0',
    appId: '1:767423513180:ios:e39bee403f8e9e7de61c99',
    messagingSenderId: '767423513180',
    projectId: 'breedward1',
    databaseURL: 'https://breedward1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedward1.firebasestorage.app',
    iosClientId: '767423513180-pi0es8p0ji701reubuub6t3nns74dfli.apps.googleusercontent.com',
    iosBundleId: 'com.example.breedward',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtvK-1igcyina-QfsT-EB4xP2vJCuncxo',
    appId: '1:767423513180:web:9cb56c793bbc7a2ae61c99',
    messagingSenderId: '767423513180',
    projectId: 'breedward1',
    authDomain: 'breedward1.firebaseapp.com',
    databaseURL: 'https://breedward1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'breedward1.firebasestorage.app',
    measurementId: 'G-DLXBE0QDPW',
  );

}